name: TFApplyLandingZone

on:
  push:
    paths:
    - 'migration/**'

jobs:
  tfapply:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: nil0blue/terraform-azure-pipeline@v1
      with:
        arm_client_id: ${{ secrets.ARM_CLIENT_ID }}
        arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}
        arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}
        arm_access_key: ${{ secrets.ARM_ACCESS_KEY }}
        variables: "storage_account_name=farzterraformstate,container_name=terraform"
        path: migration
        varfile: foundation.tfvars
